title: Koh Jin Hong, Lucas - Engineering Portfolio
author:
  name: Koh Jin Hong, Lucas
  email: jinhongkh@gmail.com # Replace with your actual email
description: >-
  Portfolio of Koh Jin Hong, Lucas, an Electronic Engineering Master's candidate.
  Showcasing projects in networking, firmware automation, and backend development.
baseurl: "" # For username.github.io
url: "https://lucasjinhong.github.io" # Replace 'lucasjinhong' with your GitHub username

# Minima theme specific settings
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: lucasjinhong  # Replace with your GitHub username
    linkedin: lucasjinhong # Replace with your LinkedIn username (the part after linkedin.com/in/)
    # To add email to social links (optional)
    # - { platform: email, user_url: "mailto:jinhongkh@gmail.com" }


# Header pages (navigation links)
header_pages:
  - about.md
  - projects.md
  - assets/resume_koh_jin_hong_lucas.pdf # Direct link to resume in navigation

# Build settings
theme: minima # If GitHub Pages doesn't automatically pick it up, or for local build
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.md